apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
  name: example-kyma-serverless-function-python
spec:
  url: "https://github.com/eduardoarndt/example-kyma-serverless-function-python"
